[package]
name = "fauxchat"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["usergen", "twitch", "commands"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
actix-files = "0.6.2"
actix-web = "4.3.1"
actix-web-actors = "4.2.0"
anyhow = "1.0.71"
clap = { version = "4.2.7", features = ["derive"] }
const_format = "0.2.30"
lazy_static = "1.4.0"
rand = "0.8.5"
rayon = "1.7.0"
reqwest = { version = "0.11.13", features = ["json"] }
rotenv_codegen = "0.15.0"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
thiserror = "1.0.40"
tokio = { version = "1.28.0", features = ["full"] }
toml = "0.7.3"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"

twitch_api = { path = "twitch" }
usergen = { path = "usergen" }
commands = { path = "commands" }

[build-dependencies]
rotenv_codegen = "0.15.0"
serde = { version = "1.0.162", features = ["derive"] }
toml = "0.7.3"
